apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Chart.Name .Values.fullnameOverride }}
  labels:
    {{- include "test-go-app-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "test-go-app-chart.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "test-go-app-chart.selectorLabels" . | nindent 12 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}