apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-go-app-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 8 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: test-go-app-service
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}