# templates/serviceaccount.yaml
{{- if .Values.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iamRoleArn }}
{{- end }}
