apiVersion: v1
kind: Service
metadata:
  name: {{ include "MTLTest.fullname" . }}
  labels:
    {{- include "MTLTest.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "MTLTest.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}