apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-go-app-chart.fullname" . }}
  labels:
    {{- include "test-go-app-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "test-go-app-chart.selectorLabels" . | nindent 8 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}