apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-go-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: your-namespace  # Replace with your Kubernetes namespace
  project: default
  source:
    repoURL: https://github.com/your-username/your-repo  # Replace with your GitHub repository URL
    targetRevision: HEAD
    path: path/to/your/helm/charts  # Path to your Helm charts directory in the repository
    helm:
      valueFiles:
        - values.yaml  # Optionally, specify path to your values file if needed
  syncPolicy:
    automated:
      prune: true  # Enable automatic pruning of resources not in Git
      selfHeal: true
