# Deployment strategy options: simple, canary, blue-green
deploymentStrategy: blue-green

# Configuration options for Simple Deployment
simple:
  replicaCount: 1            # Number of replicas for the application
  image:
    repository: makokja/test-go-app
    pullPolicy: IfNotPresent
    tag: "1.0"

# Configuration options for Canary Deployment
canary:
  enabled: false           # Set to true to enable Canary Deployment
  steps: 5                   # Number of steps for Canary Deployment
  trafficWeight: 20          # Initial weight for canary traffic (percentage)
  incrementWeight: 20        # Incremental weight for each step (percentage)
  interval: 10               # Interval between steps in seconds
  scaleDownDelay: 60         # Delay in seconds before scaling down the old version

# Configuration options for Blue-Green Deployment
blueGreen:
  enabled: true           # Set to true to enable Blue-Green Deployment
  scaleUpDelay: 60           # Delay in seconds before scaling up the new version
  scaleDownDelay: 60         # Delay in seconds before scaling down the old version
  image:
    repository: makokja/test-go-app
    pullPolicy: IfNotPresent
    tag: "1.0"

# Service configuration
service:
  type: ClusterIP            # Kubernetes service type
  port: 80                   # Port on which the service listens
  targetPort: 8080           # Port on which the application listens

# Ingress configuration
ingress:
  enabled: false             # Set to true to enable Ingress
  annotations:               # Ingress annotations (if any)
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /                    # Path on which the application is served
  hosts:                     # List of hosts for the Ingress
    - goapp.example.com

autoscaling:
  enabled: false  # Set to true to enable Horizontal Pod Autoscaler


